baseURL: 'https://andrelimzs.github.io'
languageCode: 'en-us'
title: 'AndreLimZS'
theme: 'PaperMod'

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: AndreLimZS
    #description: "Example"
    author: Andre Lim

    # homeInfoParams:
    #     Title: Andre Lim ZS
    #     Content: Algorithm Engineer

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    ShowWordCount: true
    ShowRssButtonInSectionTermList: false
    UseHugoToc: true
    disableSpecial1stPost: true
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: true

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Andre Lim ZS
        subtitle: "Algorithm Engineer"
        imageUrl: "profile_pic.jpg"
        imageWidth: 240
        imageHeight: 240
        imageTitle: my image
        buttons:
            - name: Machine Learning
              url: /posts/machine-learning
              imageUrl: "machine_learning.jpg"
            - name: CNC Machine
              url: /posts/cnc-mill
              imageUrl: "V9_1_transparent-1.png"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: Machine Learning
      name: Machine Learning
      url: posts/machine-learning/
      weight: 10
    - identifier: CNC Mill
      name: CNC Mill
      url: posts/cnc-mill/
      weight: 20

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary